"""intitial_migration

Revision ID: 1c681586cb35
Revises: 
Create Date: 2026-02-28 21:47:46.568432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = '1c681586cb35'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Check if tables already exist
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_tables = inspector.get_table_names()
    
    # ### commands auto generated by Alembic - please adjust! ###
    if 'problems' not in existing_tables:
        op.create_table('problems',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('domain', sa.String(length=100), nullable=False),
        sa.Column('subject', sa.String(length=100), nullable=False),
        sa.Column('topic', sa.String(length=100), nullable=False),
        sa.Column('cluster', sa.String(length=150), nullable=False),
        sa.Column('question_type', sa.String(length=50), nullable=False),
        sa.Column('cognitive_dimension', sa.String(length=100), nullable=False),
        sa.Column('difficulty_band', sa.Integer(), nullable=False),
        sa.Column('super_band', sa.Integer(), nullable=False),
        sa.Column('concepts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('skills_tested', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('problem_statement', sa.Text(), nullable=False),
        sa.Column('example_input', sa.Text(), nullable=True),
        sa.Column('example_output', sa.Text(), nullable=True),
        sa.Column('estimated_time_seconds', sa.Integer(), nullable=False),
        sa.Column('mastery_weight', sa.Float(), nullable=False),
        sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_problems'))
        )
        op.create_index(op.f('ix_problems_id'), 'problems', ['id'], unique=False)
    
    if 'users' not in existing_tables:
        op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('hashed_password', sa.String(length=255), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('role', sa.String(length=50), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
        )
        op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
        op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    
    if 'submissions' not in existing_tables:
        op.create_table('submissions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('problem_id', sa.Integer(), nullable=False),
        sa.Column('code', sa.Text(), nullable=False),
        sa.Column('language', sa.String(length=50), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('score', sa.Float(), nullable=False),
        sa.Column('execution_time_ms', sa.Integer(), nullable=True),
        sa.Column('difficulty_band', sa.Integer(), nullable=False),
        sa.Column('super_band', sa.Integer(), nullable=False),
        sa.Column('cluster', sa.String(length=150), nullable=False),
        sa.Column('skill_delta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('mastery_delta', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_submissions_problem_id_problems'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_submissions_user_id_users'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_submissions'))
        )
        op.create_index(op.f('ix_submissions_id'), 'submissions', ['id'], unique=False)
        op.create_index(op.f('ix_submissions_problem_id'), 'submissions', ['problem_id'], unique=False)
        op.create_index(op.f('ix_submissions_user_id'), 'submissions', ['user_id'], unique=False)
        op.create_index('ix_submissions_user_problem', 'submissions', ['user_id', 'problem_id'], unique=False)
    
    if 'test_cases' not in existing_tables:
        op.create_table('test_cases',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('problem_id', sa.Integer(), nullable=False),
        sa.Column('input_data', sa.Text(), nullable=False),
        sa.Column('expected_output', sa.Text(), nullable=False),
        sa.Column('is_hidden', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_test_cases_problem_id_problems'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_test_cases'))
        )
        op.create_index(op.f('ix_test_cases_id'), 'test_cases', ['id'], unique=False)
        op.create_index(op.f('ix_test_cases_problem_id'), 'test_cases', ['problem_id'], unique=False)
    
    if 'user_skill_state' not in existing_tables:
        op.create_table('user_skill_state',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('skill_name', sa.String(length=150), nullable=False),
        sa.Column('current_mastery', sa.Float(), nullable=True),
        sa.Column('super_band', sa.Integer(), nullable=True),
        sa.Column('total_attempts', sa.Integer(), nullable=True),
        sa.Column('total_success', sa.Integer(), nullable=True),
        sa.Column('last_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_skill_state_user_id_users'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_user_skill_state'))
        )
        op.create_index(op.f('ix_user_skill_state_id'), 'user_skill_state', ['id'], unique=False)
        op.create_index(op.f('ix_user_skill_state_user_id'), 'user_skill_state', ['user_id'], unique=False)
        op.create_index('ix_user_skill_state_user_skill', 'user_skill_state', ['user_id', 'skill_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_skill_state_user_skill', table_name='user_skill_state')
    op.drop_index(op.f('ix_user_skill_state_user_id'), table_name='user_skill_state')
    op.drop_index(op.f('ix_user_skill_state_id'), table_name='user_skill_state')
    op.drop_table('user_skill_state')
    op.drop_index(op.f('ix_test_cases_problem_id'), table_name='test_cases')
    op.drop_index(op.f('ix_test_cases_id'), table_name='test_cases')
    op.drop_table('test_cases')
    op.drop_index('ix_submissions_user_problem', table_name='submissions')
    op.drop_index(op.f('ix_submissions_user_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_problem_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_problems_id'), table_name='problems')
    op.drop_table('problems')
    # ### end Alembic commands ###
